version: '3.8'
services:
  app:
    container_name: payment-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8190:8080
    depends_on:
      - db
      - queue
    networks:
      - dockerNet
  db:
    container_name: payment-db
    image: mongodb/mongodb-community-server:latest
    ports:
      - 8191:27017
  queue:
    container_name: central-queue
    image: rabbitmq:3.13.0-rc.2-management
    ports:
      - 8200:5672
      - 8201:15672
    environment:
      RABBITMQ_DEFAULT_USER: test-user
      RABBITMQ_DEFAULT_PASS: test-user
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - dockerNet

networks:
  dockerNet:
    external:
      true
